DATASET_DIR: "."
TRAIN_JSON_PATH: ".\\train.json"
TEST_JSON_PATH: ".\\test.json"
BATCH_SIZE: 4
OUTPUT_SIZE: 2
MAX_SEQ_LEN: 512
EMBEDDING_DIMENSION: 512
POOLING_METHOD: "mean"
NUM_HEADS: 8
EXPANSION_FACTOR: 4
NUM_BLOCKS: 2
ACTIVATION: "gelu"
DROPOUT: 0.1
MODEL_SAVE_PATH: "C:\\Users\\dell\\my_projects\\projectG\\mymodel"
LOSS_FN_TYPE: "cel"
OPTIMIZER_TYPE: "radam"
NUM_EPOCHS: 4
LEARNING_RATE: 1e-3
WEIGHT_DECAY: 1e-5
GAMMA: 0.1
